### ISSUE TITLE
 Unable to find a signing key that matches: "None"

### ISSUE THREAD

**Issue by kolserdav** [fixie-ai/fixie-sdk#126]
I started the agent on the local server with the `fixie agent serve` command.
Then I try to make a request to it like this:
```sh
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer [TOKEN]" -d '{"message":{"text":"time"}}' http://localhost:8181/func
```
I get this response:
```sh
Internal Server Error
```
Server log:
```sh

INFO:     127.0.0.1:34808 - "POST /func HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fixieai/agents/agent_base.py", line 194, in _serve_func
    token_claims = self.validate_token_and_update_query_access_token(
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fixieai/agents/agent_base.py", line 168, in validate_token_and_update_query_access_token
    token_claims = VerifiedTokenClaims.from_token(
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/fixieai/agents/agent_base.py", line 252, in from_token
    public_key = jwks_client.get_signing_key_from_jwt(token)
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/jwt/jwks_client.py", line 97, in get_signing_key_from_jwt
    return self.get_signing_key(header.get("kid"))
  File "/home/kol/Projects/fixie-agent/.fixie.venv/lib/python3.10/site-packages/jwt/jwks_client.py", line 87, in get_signing_key
    raise PyJWKClientError(
jwt.exceptions.PyJWKClientError: Unable to find a signing key that matches: "None"
```

**Comment by kolserdav** [comment]
I displayed this token https://github.com/fixie-ai/fixie-sdk/blob/fb8716bc21a82ba7fea8d1c6eed5d437eed8d272/fixieai/agents/agent_base.py#L246 in the console and saw that the token that is sent to the server when the agent is launched differs in its semantics from what I received in my personal account. By substituting this token into the request, the problem was miraculously solved.
