### ISSUE TITLE
pixie agent serve fails without a clear error message

### ISSUE THREAD

**Issue by yvesjunqueira** [fixie-ai/fixie-sdk#152]
```
$ fixie agent serve
Opening tunnel to 0.0.0.0:8181 via localhost.run.
This replaces any existing deployment, run fixie deploy to redeploy to prod.

Traceback (most recent call last):
  File "/Users/yves/opt/anaconda3/envs/gpt/bin/fixie", line 8, in <module>
    sys.exit(fixie())
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/yves/opt/anaconda3/envs/gpt/lib/python3.10/site-packages/fixieai/cli/agent/commands.py", line 424, in serve
    config.deployment_url = next(deployment_urls_iter)
StopIteration
```

Perhaps the tunnel creation is failing because it's getting blocked by my corp firewall. It would be nice if the error message was clearer.

**Comment by petersalas** [comment]
Thank you @yvesjunqueira! You're correct -- the tunnel is failing to connect. I'll make the error message more clear.
